server:
  port: 8089
spring:
  datasource:
    dynamic:
      primary: master
      strict: true
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          druid:
            validation-query: select 1
          url: jdbc:mysql://mysql-dev:3306/reststyle?&serverTimezone=GMT%2B8
          username: root
          password: 123456
      #  多数据源如下配置
        oracle:
          driver-class-name: oracle.jdbc.driver.OracleDriver
          druid:
            validation-query: select * from dual
          url: jdbc:oracle:thin:@oracle-dev:1521/orcl
          username: sys
          password: 123456
  # 查询时间数据 数据库和返回数据相差8个小时
  jackson:
    time-zone: GMT+8
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl